"""empty message

Revision ID: 189b1da162e8
Revises: 37ac8b01bdc8
Create Date: 2024-09-27 17:31:37.640100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189b1da162e8'
down_revision = '37ac8b01bdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_detail_info', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_detail_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
