"""empty message

Revision ID: 37ac8b01bdc8
Revises: 50fb4f99b545
Create Date: 2024-09-26 20:51:25.790154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ac8b01bdc8'
down_revision = '50fb4f99b545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mytravel',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('travelplan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travelplan_id'], ['travelplan.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'travelplan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mytravel')
    op.drop_table('travelplan')
    # ### end Alembic commands ###
