"""empty message

Revision ID: 50fb4f99b545
Revises: 571f0052a832
Create Date: 2024-09-26 17:34:34.593486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fb4f99b545'
down_revision = '571f0052a832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeinfo', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
