"""empty message

Revision ID: 571f0052a832
Revises: 88bd2ac9080a
Create Date: 2024-09-26 17:16:57.445292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571f0052a832'
down_revision = '88bd2ac9080a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placeinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('myplace',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('placeinfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['placeinfo_id'], ['placeinfo.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'placeinfo_id')
    )
    op.drop_table('place_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=20), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('myplace')
    op.drop_table('placeinfo')
    # ### end Alembic commands ###
