"""empty message

Revision ID: 9e896bddf78b
Revises: 0500c6a827ed
Create Date: 2024-09-28 13:52:03.882575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e896bddf78b'
down_revision = '0500c6a827ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('myinquiry',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inquiryinfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquiryinfo_id'], ['inquiry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'inquiryinfo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myinquiry')
    op.drop_table('notice')
    op.drop_table('inquiry')
    # ### end Alembic commands ###
