"""empty message

Revision ID: f505765394b6
Revises: 9e896bddf78b
Create Date: 2024-09-28 21:06:47.884316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f505765394b6'
down_revision = '9e896bddf78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productinfo', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
