"""empty message

Revision ID: f76901a0bff0
Revises: f505765394b6
Create Date: 2024-10-01 17:11:52.514770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76901a0bff0'
down_revision = 'f505765394b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placeinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    with op.batch_alter_table('travelplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travelplan', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('placeinfo', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
